name: 'GEOAxISStrategy lint'

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!gh-pages'
    tags-ignore:
      - '**'

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci --silent
      - run: npm run lint
