name: 'GEOAxISStrategy tests'

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!gh-pages'
    tags-ignore:
      - '**'

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install npm dependencies
        run: npm ci --silent
      - name: run tests
        run: |
          npm run test
